apiVersion: apps/v1
kind: Deployment
metadata:
   name: demo-app
   namespace: default
   labels:
      app: demo-app
spec:
   selector:
      matchLabels:
         app: demo-app
   replicas: 1
   template:
      metadata:
         labels:
            app: demo-app
      spec:
         imagePullSecrets:
         - name: acr-secret
         containers:
            - name: demo-app
              image: womackecr.azurecr.io/demo-app:latest
              env:
                - name: TEMPORAL_ADDRESS
                  valueFrom:
                    configMapKeyRef:
                      name: temporal-worker-config
                      key: TEMPORAL_ADDRESS
                - name: TEMPORAL_NAMESPACE
                  valueFrom:
                    configMapKeyRef:
                      name: temporal-worker-config
                      key: TEMPORAL_NAMESPACE
                - name: TEMPORAL_TASK_QUEUE
                  valueFrom:
                    configMapKeyRef:
                      name: temporal-worker-config
                      key: TEMPORAL_TASK_QUEUE
                - name: TEMPORAL_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: temporal-secret
                      key: TEMPORAL_API_KEY
                - name: AZURE_CLIENT_ID
                  valueFrom:
                    configMapKeyRef:
                      name: temporal-worker-config
                      key: AZURE_CLIENT_ID
                - name: AZURE_TENANT_ID
                  valueFrom:
                    configMapKeyRef:
                      name: temporal-worker-config
                      key: AZURE_TENANT_ID
                - name: AZURE_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: azure-secret
                      key: AZURE_CLIENT_SECRET
                - name: KEYVAULT_URL
                  valueFrom:
                    configMapKeyRef:
                      name: temporal-worker-config
                      key: KEYVAULT_URL
                - name: KEYVAULT_SECRET_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: temporal-worker-config
                      key: KEYVAULT_SECRET_NAME
              resources:
                limits:
                  cpu: "0.5"
                  memory: "512Mi"
                requests:
                  cpu: "0.2"
                  memory: "256Mi"
